### ISSUE TITLE
Request-8: Create the URDF file of SCARA robot arm 

### ISSUE THREAD

**Issue by longjie0723** [liniii31/ros_learning#10]
Create the URDF file of DENSO's SCARA robot.

- Target robot is HS-045. You can find the spec (joint configuration, dimensions, etc) here: https://www.denso-wave.com/en/robot/product/four/hs-a1.html
- Consult with [URDF tutorials](http://wiki.ros.org/urdf/Tutorials)
- Other robot's URDF may be helpful (https://github.com/ros-industrial/universal_robot/tree/kinetic-devel/ur_description )

Creating the URDF file, check if it is correct by:

- Making it visualize in Rviz
- Changing the joint angles using joint_state_publisher_gui to change the joint angle.

**Comment by liniii31** [comment]
I have done this, but i haven't used <visual>in urdf file, so it can viewed with "TF" in rviz.
Please Check.

**Comment by longjie0723** [comment]
No, creating robot's URDF and visualizing is the purpose of this task. It is not so helpful if we have only a TF tree.
We need shape of the robot to visualize, and in the future, we use it for collision detection.

- Create URDF file, and make its shape. You can use real mesh files (actually you can download them from Denso), or some combination of the primitive like cylinders and cubes is OK.

Beforehand, make #6 and #9 finished.

**Comment by liniii31** [comment]
I have created the URDF file for target robot.Please Check

**Comment by rsedawi24** [comment]
can you please share the urdf fie for this scara robot with meshes.
