### ISSUE TITLE
request-3: set  my account as a collaborator of this repository

### ISSUE THREAD

**Issue by longjie0723** [liniii31/ros_learning#3]
This is an issue to help you to get used to GitHub.
Please add  my account (longjie0723) as a collaborator to this repository. This is helpful as to make a branch and pull requests.

**Comment by longjie0723** [comment]
Please consult google or GitHub documents to see how to set the collaborator. Please ask me if you cannot find it.

**Comment by liniii31** [comment]
I have sent an invite to you to be a collaborator, please check.

**Comment by longjie0723** [comment]
Thank you, now I am a collaborator.
