### ISSUE TITLE
Request-4: Make the rosparam parameters

### ISSUE THREAD

**Issue by longjie0723** [liniii31/ros_learning#5]
Currently,  the periodic rate of the main loop, the angular velocity and the radius of the circle are all constants in the code.
Make these parameter as rosparam, which is explained in the tutorial (http://wiki.ros.org/rospy_tutorials/Tutorials/Parameters). 

1. Modify the code to use rosparams
2. Set these parameter in launch file
3. Confirm these parameter set correctly with `rosparam list` and `rospamra get` in commandline

Please let me know here when you've done.

**Comment by liniii31** [comment]
I have Done this. Please Check

**Comment by longjie0723** [comment]
Can you change the periodic rate either? Currently it is 10 [Hz]. Please notice I wrongly increased the step tick (it should be 0.1 at 10[Hz]).

**Comment by liniii31** [comment]
Yes , updated . Please check.

**Comment by longjie0723** [comment]
Well done.
