### ISSUE TITLE
Request-6: Get used to GitHub flow

### ISSUE THREAD

**Issue by longjie0723** [liniii31/ros_learning#7]
Until now, you pushed your change to your master branch directly. It is no problem when you are the only one to modify the repository. Most developments are done with collaborators, so now we need better way. We hires "GitHub flow" in our software development.

Please read [the guide](https://guides.github.com/introduction/flow/) and understand the concept. If you can, please make branches and pull requests for the future issues.

Close this when you think you can get the concept of GitHub flow.

**Comment by liniii31** [comment]
I think i have understood the concept of Github flow.
